security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            logout:
                path: /logout
                target: /
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                login_path: /login
                use_forward: false
                failure_path: /login
                default_target_path: /home

                oauth_user_provider:
                   service: app.user.provider.fosuser

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
